homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: !secret elevation
  unit_system: metric
  time_zone: !secret time_zone
telegram_bot: !include telegram.yaml
logger:
  default: info
default_config:
#https://home-assistant.io/components/config
config:
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

#https://home-assistant.io/components/history/
history:
media_player: !include_dir_merge_list media_player/
binary_sensor: !include_dir_merge_list binary_sensors/